name: "Publish every Git push to master to FlakeHub"
on:
  push:
    branches:
      - "master"
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v3"
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "juliens/flakes"
          rolling: true
          visibility: "unlisted"
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build
